### ISSUE TITLE
How to do test when I add model/realsr into original edsr-pytorch repo?

### ISSUE THREAD

**Issue by Senwang98** [Alan-xw/RealSR#12]
Hi, @Alan-xw 
I didn't use your repo to train realsr,  I used original edsr-pytorch instead.
I first pre-upscale the input x so that the output size is original size * args.scale.
the training process is ok, but when test PSNR on Set5 each epoch, something wrong happened.
```
model/common.py", line 39, in _space_to_channel
    x = x.contiguous().view(b, C, hout, scale, wout, scale)
RuntimeError: shape '[1, 4, 65, 4, 67, 4]' is invalid for input of size 280800
```

**Comment by Senwang98** [comment]
When I do test, if the input size of X is (260,270), then 270 % 4 != 0.
You know how to solve this problem?

**Comment by Songtingt** [comment]
> When I do test, if the input size of X is (260,270), then 270 % 4 != 0.
> You know how to solve this problem?

hello, i have the same question, have you  solved it？
